### ISSUE TITLE
Distribute as a single file 

### ISSUE THREAD

**Issue by walkah** [fission-suite/webnative#173]
For simple HTML / JS apps (without a build process - webpack / etc) it would be nice to just include webnative via a script tag.

Our rollup config already can generate an index.umd.js ... but it should probably be minified (currently around 2.1M) and made available (over IPFS, of course).

**Comment by icidasset** [comment]
Temporary solution:
```html
<script src="https://bundle.run/webnative"></script>
```
Tested on codepen.io

**Comment by matheus23** [comment]
I was just working on the rollup configuration right now, so I quickly tried minifying the .umd build with terser, and... it's better now?
"Only" 500kb?

Not sure if it can be improved.

**Comment by Jermolene** [comment]
Perhaps the size of webnative.js wouldn't be an issue for most clients – it looks like https://drive.fission.codes/web_modules/webnative.js isn't GZip compressed at the moment, but if it were I think it would come in at about 164kb instead of 590kb.

It would only become a consideration for TiddlyWiki if we embed the library. That's our usual approach to enable us to support offline operation as a self-contained file (we can't use a service worker because of the need to be able to move TiddlyWiki files between browsers while offline). I am interested in tapping Fission's offline capabilities, so I'll proceed with embedding the bundled version for the moment.

**Comment by matheus23** [comment]
@Jermolene I took a look at this in #170 

Once we publish the new version of webnative, there's going to be a `dist/index.umd.min.js.gz` which is at around ~157kb.

Just to give you an update :)

**Comment by Jermolene** [comment]
Thanks @matheus23 that's great.
