### ISSUE TITLE
NPM install issue missing dependency

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#260]
## Problem

```
│ sh: rimraf: command not found
│ npm ERR! code ELIFECYCLE
│ npm ERR! syscall spawn
│ npm ERR! file sh
│ npm ERR! errno ENOENT
│ npm ERR! base58-universal@1.0.1-0 clear: `rimraf dist && mkdir dist`
│ npm ERR! spawn ENOENT
│ npm ERR! 
│ npm ERR! Failed at the base58-universal@1.0.1-0 clear script.
```
Because we're currently using a git dependency for `base58-universal`, it tries to run it's build task, resulting in a missing dependency.

## Solution

1. Don't use a git dependency
2. Add `rimraf` as a dependency along side your `webnative` dependency

**Comment by matheus23** [comment]
I've looked into this a little. We *might* not need the `base58-universal` dependency.
We're using [uint8arrays](https://github.com/achingbrain/uint8arrays) and they support all bases that [multibase](https://github.com/multiformats/js-multiformats#multibase-encoders--decoders--codecs) support (since version 2.1.6 as far as I understand), and `base58btc` is among them.
