### ISSUE TITLE
Use AES-GCM everywhere

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#289]
Unless we have a specific reason to, we should be using AES-GCM across the board. Safari is giving me this warning:

<img width="1174" alt="Screen Shot 2021-09-27 at 15 08 11" src="https://user-images.githubusercontent.com/1052016/134991996-440955e0-0a70-4ec1-a4f5-9d58c501e892.png">

There's some open questions about if we GCM is overkill when we have integrity hashes from IPFS, but it can't hurt in the meantime. We've discussed this internally previously, and I thought we had already switched over to GCM. We should double check.

Possible that it's just picking up on this with a naive scan of the source? https://github.com/fission-suite/webnative/blob/26dcae9e4a8f0145e62648984ae29dccb374a02b/src/lobby/blocklist.ts#L73-L77

**Comment by matheus23** [comment]
> Possible that it's just picking up on this with a naive scan of the source? 

I've been confused by the encryption code before, because my info was that we're using AES-GCM, but we're instantiating keystore-idb in a way such that I think we're actually using AES-CTR:

https://github.com/fission-suite/webnative/blob/16af87446f68bf8d3c367a04abeb3f67e57e40a5/src/crypto/browser.ts#L11-L16

Notice how on line 14 we're not providing a specific "algorithm" option here, so the default symmetric algorithm in keystore-idb is used. Which is [`AES-CTR`](https://github.com/fission-suite/keystore-idb/blob/6e4b3d54dc983611a38c944ee9243e44be03f6df/src/constants.ts#L13) (used [here](https://github.com/fission-suite/keystore-idb/blob/6e4b3d54dc983611a38c944ee9243e44be03f6df/src/aes/operations.ts#L13)).

**Comment by matheus23** [comment]
Do we want to switch that algorithm out in WNFS V1?
Because that'd be a breaking change, unless we'd add some compatibility layer.

**Comment by icidasset** [comment]
We definitely haven't switched yet, issue on keystore-idb is still open: https://github.com/fission-suite/keystore-idb/issues/39

Reasons we haven't switched yet:
1. Breaking change, need upgrade path for filesystem.
2. I think Daniel said something about streaming encryption/decryption and picking CTR for that reason.

**Comment by icidasset** [comment]
He also mentioned that here: https://github.com/fission-suite/keystore-idb/issues/16

**Comment by matheus23** [comment]
Okay. So TLDR, we used AES-CTR to have a plan for streaming.

There's two more ways to support streaming that came out of the exploratory work with wnfs-go. It's always about how we chop up files into chunks that we can stream. These two other options came up:

* Do the chunking at the IPFS chunker level (at the configured ipfs chunk size, which is like 1MB max I think). I.e. wnfs-go's Cypherchunker.
* Chunk files into blocks which all get their own namefilter. We would do this to hide how big files in the user's filesystem are and thus make it harder to fingerprint users.

Minor note: As far as I can tell all 3 approaches enable random access.

In terms of performance, using AES-CTR or doing it at the IPFS Chunker layer will most likely be more performant (no need to calculate namefilters).

In terms of privacy, chunking files into private filesystem blocks wins.

---

Also worth noting that the third approach is what we put in the spec so far (see the [`Content` data type on this page](https://whitepaper.fission.codes/file-system/partitions/private-directories/platform-layer#unlocked-private-node-schema) and the 'Content Access' section below).

**Comment by expede** [comment]
> Okay. So TLDR, we used AES-CTR to have a plan for streaming.

[Context: AES-GCM is AES-CTR plus a MAC]

@matheus23 we can actually use GCM for streaming, since we'd be breaking up the file into chunks that can be separately MACed. Given the size of a seekable chunk, the performance overhead won't be noticeable. The bigger question is if we get that from the MAC since we have CIDs. I think it should be fine, but we should talk to an expert. Until then AES-GCM is the common wisdom as being strictly better than AES-CTR.

**Comment by expede** [comment]
Probably worth noting that we'd need to do an IV per chunk as well, so IV + MAC per chunk seem very reasonable to me. Thoughts?

**Comment by matheus23** [comment]
Oh yeah right. Option 2 and 3 totally don't need AES-CTR. We can use AES-GCM with very little overhead.

**Comment by matheus23** [comment]
So the way I understand this now is: The current plan is to go for Option 3 (file chunks under different namefilters) and because that's breaking & we're not adding a compatibility layer, we'll schedule that for WNFSv2.

**Comment by expede** [comment]
> The current plan is to go for Option 3 (file chunks under different namefilters) and because that's breaking & we're not adding a compatibility layer, we'll schedule that for WNFSv2.

For file streaming? Yes. We should still move to AES-GCM as soon as possible for non-streaming files as well.

**Comment by matheus23** [comment]
> We should still move to AES-GCM as soon as possible for non-streaming files as well

Okay, so I interpret "as soon as possible" to be within wnfs v1.

So that means we need a compatibility layer. We need
1. A way to annotate private filesystem blocks with the algorithm used so we know whether we have to decrypt using AES-CTR or AES-GCM
2. To encrypt new filesystem blocks with AES-GCM.

This is a breaking WNFS update, which means all apps that stay on webnative version 28 or below will stop working once a user has used e.g. drive with webnative version 29 (or whatever will include the AES-GCM update).

---

I think this might be a bit drastic. Maybe I misunderstood and the intention was to go fully AES-GCM starting with WNFSv2?

**Comment by expede** [comment]
@matheus23 

> Okay, so I interpret "as soon as possible" to be within wnfs v1.

Yup, unless v2 is very close, which I don't believe is the case

> A way to annotate private filesystem blocks with the algorithm used so we know whether we have to decrypt using AES-CTR or AES-GCM

The algorithm is tracked in decryption pointers, not on the file itself. If there's no algorithm listed, treat it as AES-CTR. Otherwise use whatever is in the algorithm field (AES-GCM).

> This is a breaking WNFS update

This is a fully backwards-compatible change. Yes, apps will need to update to the latest webnative if their data is shared with apps that have a newer version (infrequent at best today). We do this kind of thing frequently. The semver would be a minor version increment.

**Comment by expede** [comment]
> @expede I assume that when the auth lobby grants private file/directory permissions, it should now both share the symmetric `key` to decrypt the node, as well as the `algorithm`, right? Otherwise webnative wouldn't know whether the file/directory is AES_CTR or AES_GCM encrypted.

Yes, exactly. Alternatively if we put the mode on the file itself (I think we have that in the Talk thread), that also solves the problem

**Comment by expede** [comment]
> I think the idea would be that you'd use an asymmetric key to encrypt your CEK. In our case it complicates the whole situation a little: We'd have an addition symmetric key indirection in here.

Yeah, that doesn't make sense for our use case. We do key management elsewhere.

> I think for now it would make sense to use our own CBOR-based format that just lists the algorithm (and possibly the IV).

Agreed on algorithm, IV, and payload 👍

**Comment by expede** [comment]
I suppose we'd also break out the MAC (AKA "authentication tag")

**Comment by expede** [comment]
Also also: I suppose CBOR because it's easy for us to standardize on and use everywhere, ya? _This_ wrapper is quite small, but there's also Protobufs, Avro, Thrift, and more that have reasonable levels of support. Any opinions?

**Comment by matheus23** [comment]
I like CBOR, because
1. We already use it (for the private filesystem)
2. It has good support in the ipfs ecosystem in general (e.g. things like encoding CIDs in CBOR out of the box & a library maintained by PL)

Everything else would need us adding another dependency.

---

> I suppose we'd also break out

For now I went with only two keys in the CBOR record: `alg` for a string indicating the algorithm and `cip` for the ciphertext, which then includes IV and MAC. (for AES-GCM).

Getting the iv out of there is easy (and something I planned to do, it's just a little more involved, because I'd have to crack open keystore-idb), but I'm not sure how to get the MAC out of there, since it's put there by WebCrypto. Possibly a standard and appended to the beginning/end?
