### ISSUE TITLE
Implement skip ratchet

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#309]
https://whitepaper.fission.codes/file-system/partitions/private-directories/concepts/spiral-ratchet

My understanding is that this code actually exists, but needs to be split out from its existing branch

**Comment by therealjeffg** [comment]
@matheus23 is this still necessary now that we have the rs version.

**Comment by matheus23** [comment]
@therealjeffg yeah we never closed this because it never made it to "production", but yes. There now exist 2 skip ratchet implementations, [one in TS](https://github.com/fission-suite/webnative/blob/matheus23/wnfs2/src/fs/data/private/spiralratchet.ts) and [one in RS](https://github.com/WebNativeFileSystem/rs-skip-ratchet/).

**Comment by matheus23** [comment]
Implemented in a ts prototype at the `wnfs2` branch in this repo, or as a rust version at https://github.com/webnativeFileSystem/rs-skip-ratchet/
