### ISSUE TITLE
Registering via auth lobby fails on Brave fails

### ISSUE THREAD

**Issue by nathanmalishev** [fission-suite/webnative#84]
# Summary
Creating a new user on the `Brave browser` fails.

## Problem
Throws this error `Public key MIIB...QAB already exists`
Which is when the function call `mkdir` fails out. 

### Impact

Brave users can not register to the service

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: macbook pro
 - OS: macOS 10.15.6
 - Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

**Comment by bmann** [comment]
Thanks for reporting @nathanmalishev  — does it work on Safari and/or Chrome for you on the same machine?

Sound like Brave implements WebCrypto API differently - or blocks it. Will research of this is a known issue.

**Comment by icidasset** [comment]
Hmm, it worked for me, but I've never used Brave before.

Few questions:
- Are these errors in the auth lobby or your app?
- Did you make an account before this?
- Can you tell us more about `Which is when the function call mkdir fails out.`?

**Comment by nathanmalishev** [comment]
To answer the questions 
- These are in the auth lobby specifically (both in my app when integrating the SDK & on the quotes app)
- I'm not sure honestly I think i must of
- So I was mistaken I thought that the error that was being thrown was from the call `mkdir` as I thought the error was coming from there `Path already exists` - but the error here is `Public key *key* already exists`. Which actually comes from the API.
![image](https://user-images.githubusercontent.com/7652207/90456146-7629ea80-e13b-11ea-81a9-af5a59171b59.png).
So it may be not sdk related..?

But it works perfectly on safari & chrome & also **brave in incognito mode.**

**Comment by icidasset** [comment]
You'll get that `409` status from the API when an account with that DID already exists.

What happens is:
- You visit the auth lobby, a public-private key pair is generated
- The public key is used to make your DID (decentralised identifier)
- When you create an account, this DID is used to identify you.
   In other words, this DID is unique to this domain, on that browser, on that device.

So that means you already used that DID to make an account.
If you'd like to remove your pub-priv key pair to make a new DID, remove the key in your indexeddb.

Let me know if that makes sense.

**Comment by nathanmalishev** [comment]
@icidasset 🎆 
You are indeed correct. After clearing the browsers storage for that site the issue is resolved.
I can't seem to get it back into that error state - I guess we can go ahead and close the issue
